// Centralized Plan Tiers Catalog categorized by Product Track (Ofia AI, Ofia Shop, Ofia Enterprise Suite, Ofia Compass)
export interface SubscriptionTierItem {
  id: string;
  category: "OFIA_AI" | "OFIA_SHOP" | "OFIA_ENTERPRISE" | "OFIA_COMPASS";
  categoryLabel: string;
  tier: string;
  name: string;
  priceNgn: number;
  period: string;
  badge: string;
  description: string;
  leadsLimit: number;
  campaignsLimit: number;
  teamSeats: number;
  tokensLimit?: number;
  storefrontsLimit?: number;
  features: string[];
}

export const SUBSCRIPTION_TIERS_CATALOG: SubscriptionTierItem[] = [
  // 1. OFIA AI SUBSCRIPTIONS
  {
    id: "ofia-ai-pilot",
    category: "OFIA_AI",
    categoryLabel: "Ofia AI",
    tier: "FREE_TRIAL",
    name: "Ofia AI Pilot",
    priceNgn: 0,
    period: "14 Days",
    leadsLimit: 250,
    campaignsLimit: 1,
    teamSeats: 2,
    tokensLimit: 250000,
    badge: "14-Day Pilot",
    description: "Sandbox for testing autonomous AI SDR agents and lead discovery.",
    features: [
      "1 Autonomous AI Outreach Agent",
      "250 Verified Enrichment Leads",
      "250k Monthly AI Tokens Quota",
      "Email Discovery Channel",
    ],
  },
  {
    id: "ofia-ai-growth",
    category: "OFIA_AI",
    categoryLabel: "Ofia AI",
    tier: "STARTER",
    name: "Ofia AI Growth Swarm",
    priceNgn: 13000,
    period: "Monthly",
    leadsLimit: 5000,
    campaignsLimit: 5,
    teamSeats: 5,
    tokensLimit: 10000000,
    badge: "Most Popular AI",
    description: "Autonomous GTM swarm for multi-channel sales and WhatsApp agents.",
    features: [
      "5 Autonomous AI Swarm Agents",
      "5,000 Verified Enrichment Leads / mo",
      "10M Monthly AI Tokens Quota",
      "Email + WhatsApp SDR Pipelines",
      "BYOK OpenAI & Anthropic",
    ],
  },
  {
    id: "ofia-ai-scale",
    category: "OFIA_AI",
    categoryLabel: "Ofia AI",
    tier: "GROWTH",
    name: "Ofia AI Autonomous Scale",
    priceNgn: 36000,
    period: "Monthly",
    leadsLimit: 25000,
    campaignsLimit: 20,
    teamSeats: 15,
    tokensLimit: 50000000,
    badge: "High Velocity AI",
    description: "Enterprise swarm intelligence for high-velocity revenue generation.",
    features: [
      "20 Autonomous Swarm Agents",
      "25,000 Verified Leads / mo",
      "50M Monthly AI Tokens Quota",
      "LinkedIn + Meta Ads + Voice AI SDRs",
      "Custom Brand Tone Fine-Tuning",
    ],
  },
  {
    id: "ofia-ai-sovereign",
    category: "OFIA_AI",
    categoryLabel: "Ofia AI",
    tier: "ENTERPRISE",
    name: "Ofia AI Sovereign Cluster",
    priceNgn: 70000,
    period: "Monthly",
    leadsLimit: 100000,
    campaignsLimit: 100,
    teamSeats: 50,
    tokensLimit: 200000000,
    badge: "Dedicated AI",
    description: "Dedicated GPU clusters, unlimited AI agents, and private vector storage.",
    features: [
      "Unlimited Autonomous AI Swarms",
      "100,000 Verified Leads / mo",
      "200M Monthly AI Tokens Quota",
      "Dedicated Inference GPU Cluster",
      "Private Vector Database & RAG",
    ],
  },

  // 2. OFIA SHOP SUBSCRIPTIONS
  {
    id: "ofia-shop-starter",
    category: "OFIA_SHOP",
    categoryLabel: "Ofia Shop",
    tier: "STARTER",
    name: "Ofia Shop Starter",
    priceNgn: 3000,
    period: "Monthly",
    leadsLimit: 500,
    campaignsLimit: 1,
    teamSeats: 2,
    storefrontsLimit: 1,
    badge: "Fast Launch",
    description: "Deploy branded storefront on slug.ofia.shop with POS checkout.",
    features: [
      "1 Custom Storefront on slug.ofia.shop",
      "Up to 100 Products Listed",
      "Integrated POS Terminal Checkout",
      "Automated Paystack Payment Gateway",
      "Standard Customer Support",
    ],
  },
  {
    id: "ofia-shop-pro",
    category: "OFIA_SHOP",
    categoryLabel: "Ofia Shop",
    tier: "GROWTH",
    name: "Ofia Shop Merchant Pro",
    priceNgn: 9000,
    period: "Monthly",
    leadsLimit: 2000,
    campaignsLimit: 5,
    teamSeats: 10,
    storefrontsLimit: 3,
    badge: "Commerce Scale",
    description: "Custom domain connection, multi-branch POS, and logistics courier dispatch.",
    features: [
      "Custom Domain Connection + Wildcard",
      "3 Storefront Subdomains",
      "Multi-Branch POS Terminal Checkout",
      "Automated Courier & Rider Dispatch",
      "Inventory Sync (IMS Integration)",
    ],
  },
  {
    id: "ofia-shop-empire",
    category: "OFIA_SHOP",
    categoryLabel: "Ofia Shop",
    tier: "SCALE",
    name: "Ofia Shop Multi-Brand Empire",
    priceNgn: 24000,
    period: "Monthly",
    leadsLimit: 10000,
    campaignsLimit: 15,
    teamSeats: 25,
    storefrontsLimit: 10,
    badge: "Multi-Vendor",
    description: "Multi-storefront empire architecture with automated warehouse fulfillment.",
    features: [
      "10 Custom Storefront Subdomains",
      "Multi-Vendor Sub-Account Routing",
      "Automated Warehouse Fulfillment",
      "Zero Commission Surcharge (0%)",
      "24/7 Dedicated Support",
    ],
  },

  // 3. OFIA ENTERPRISE SUITE SUBSCRIPTIONS
  {
    id: "ofia-ent-core",
    category: "OFIA_ENTERPRISE",
    categoryLabel: "Ofia Enterprise Suite",
    tier: "GROWTH",
    name: "Enterprise Core ERP",
    priceNgn: 24000,
    period: "Monthly",
    leadsLimit: 5000,
    campaignsLimit: 10,
    teamSeats: 15,
    badge: "Core Operations",
    description: "Full back-office ERP suite: CRM, Financial Accounting, IMS, and HR.",
    features: [
      "All 8 Core ERP Modules",
      "Multi-Warehouse Inventory Control (IMS)",
      "Double-Entry Financial Accounting",
      "HRM Payroll & Attendance Logs",
      "15 Concurrent User Seats",
    ],
  },
  {
    id: "ofia-ent-omni",
    category: "OFIA_ENTERPRISE",
    categoryLabel: "Ofia Enterprise Suite",
    tier: "SCALE",
    name: "Enterprise Omni-Suite",
    priceNgn: 48000,
    period: "Monthly",
    leadsLimit: 20000,
    campaignsLimit: 25,
    teamSeats: 30,
    badge: "Full Ecosystem",
    description: "Complete unified ecosystem: Full ERP Suite + Ofia Shop Storefronts + AI Swarms.",
    features: [
      "Full ERP + Shop Storefronts + AI Swarms",
      "30 Concurrent User Seats",
      "20,000 Leads Pipeline / month",
      "Custom Role-Based RBAC Permissions",
      "Integrated Fleet & Dispatch Logistics",
    ],
  },
  {
    id: "ofia-ent-sovereign",
    category: "OFIA_ENTERPRISE",
    categoryLabel: "Ofia Enterprise Suite",
    tier: "ENTERPRISE",
    name: "Enterprise Sovereign SLA",
    priceNgn: 100000,
    period: "Monthly",
    leadsLimit: 50000,
    campaignsLimit: 100,
    teamSeats: 999,
    badge: "Dedicated Cloud",
    description: "Maximum throughput, dedicated cloud infrastructure, and 24/7 SLA.",
    features: [
      "Dedicated MySQL & Redis Instances",
      "99.99% Guaranteed SLA Uptime",
      "Unlimited Seats & Workspaces",
      "Custom Enterprise ERP Integrations",
      "Dedicated Strategic Technical Lead",
    ],
  },

  // 4. OFIA COMPASS SUBSCRIPTIONS (Executive Strategic BI)
  {
    id: "ofia-compass-starter",
    category: "OFIA_COMPASS",
    categoryLabel: "Ofia Compass",
    tier: "STARTER",
    name: "Ofia Compass Essentials",
    priceNgn: 7000,
    period: "Monthly",
    leadsLimit: 1000,
    campaignsLimit: 2,
    teamSeats: 3,
    badge: "Executive Radar",
    description: "Real-time executive dashboards, anomaly tracking, and automated revenue digests.",
    features: [
      "Real-Time Executive KPI Dashboard",
      "Automated Revenue & Churn Forecasts",
      "Weekly AI Market Digest Reports",
      "3 Executive / Leadership Seats",
    ],
  },
  {
    id: "ofia-compass-pro",
    category: "OFIA_COMPASS",
    categoryLabel: "Ofia Compass",
    tier: "GROWTH",
    name: "Ofia Compass Strategic Pro",
    priceNgn: 19000,
    period: "Monthly",
    leadsLimit: 5000,
    campaignsLimit: 10,
    teamSeats: 10,
    badge: "Predictive BI",
    description: "Cross-organization predictive analytics, anomaly alerts, and market trend radar.",
    features: [
      "Cross-Channel Market Trend Radar",
      "Automated Anomaly Detection & Alerts",
      "Predictive Cash Flow & Supply Models",
      "10 Executive Decision-Maker Seats",
      "Custom Dashboard Metrics Builder",
    ],
  },
  {
    id: "ofia-compass-sovereign",
    category: "OFIA_COMPASS",
    categoryLabel: "Ofia Compass",
    tier: "ENTERPRISE",
    name: "Ofia Compass Sovereign Radar",
    priceNgn: 50000,
    period: "Monthly",
    leadsLimit: 25000,
    campaignsLimit: 50,
    teamSeats: 50,
    badge: "Boardroom Intelligence",
    description: "Boardroom-ready automated presentations, strategic benchmarking, and dedicated BI analysts.",
    features: [
      "Board-Ready Automated Strategic Decks",
      "Industry Competitor Benchmarking Radar",
      "Dedicated Strategic BI Data Analyst",
      "Unlimited Executive & Board Seats",
      "24/7 Strategic Alert Notification",
    ],
  },
];
