export type VerticalLayoutTemplate =
  | "ON_DEMAND_DISPATCH"
  | "QUICK_ORDER_FOOD"
  | "CALENDAR_BOOKING"
  | "RENTAL_STAY_BOOKING"
  | "VEHICLE_INSPECTION_LISTING"
  | "SUBSCRIPTION_PICKUP"
  | "TECHNICAL_ESTIMATE_QUOTE";

export interface LayoutTemplateMeta {
  key: VerticalLayoutTemplate;
  label: string;
  badge: string;
  color: string;
  description: string;
  features: string[];
  bestFor: string[];
}

export const LAYOUT_TEMPLATES_CATALOG: Record<VerticalLayoutTemplate, LayoutTemplateMeta> = {
  QUICK_ORDER_FOOD: {
    key: "QUICK_ORDER_FOOD",
    label: "Quick-Order Restaurant / Kitchen",
    badge: "Food & Menu",
    color: "#EF4444",
    description: "Visual item menu grid, instant cart drawer, preparation time estimator, and kitchen rider dispatch.",
    features: ["Dish customization & add-ons", "Real-time kitchen order ticket", "Live delivery tracking", "Dietary badges (Halal, Vegan)"],
    bestFor: ["Food", "Culinary", "Bakery", "Private Chefs", "Bulk Food"],
  },
  CALENDAR_BOOKING: {
    key: "CALENDAR_BOOKING",
    label: "Calendar Slot & Specialist Booking",
    badge: "Appointments",
    color: "#8B5CF6",
    description: "Interactive time-slot selector, specialist staff picker, service duration calculator, and booking deposit escrow.",
    features: ["Stylist / Tutor selection", "Instant calendar availability", "Automated SMS/WhatsApp reminders", "Partial deposit escrow"],
    bestFor: ["Beauty", "Hair", "Nails", "Tutoring", "Wellness", "Caregiving", "Medical"],
  },
  ON_DEMAND_DISPATCH: {
    key: "ON_DEMAND_DISPATCH",
    label: "On-Demand Route & Fleet Dispatch",
    badge: "Rides & Courier",
    color: "#3B82F6",
    description: "Live map radius lookup, instant distance fare computation, courier dispatch desk, and waybill barcode tracking.",
    features: ["Map pickup & dropoff pins", "Automated zonal rate engine", "Live rider telemetry", "Digital proof of delivery (POD)"],
    bestFor: ["Dispatch", "Rides", "Transport", "Moving & Relocations"],
  },
  RENTAL_STAY_BOOKING: {
    key: "RENTAL_STAY_BOOKING",
    label: "Shortlet, Hotel & Apartment Stays",
    badge: "Hospitality",
    color: "#059669",
    description: "Check-in/out date range picker, nightly rate multiplier, guest count, amenity filters, and security deposit escrow.",
    features: ["Date range calendar", "High-res photo walkthroughs", "House rules agreement", "Automated security deposit hold"],
    bestFor: ["Apartments", "Hotels", "Properties", "Shortlets", "Real Estate"],
  },
  VEHICLE_INSPECTION_LISTING: {
    key: "VEHICLE_INSPECTION_LISTING",
    label: "Automotive Inspection & Workshop Bay",
    badge: "Auto & Fleet",
    color: "#D97706",
    description: "Vehicle VIN/plate lookup, mileage selector, multi-point diagnostic bay report, and quote approval.",
    features: ["VIN & engine spec lookup", "Multi-point diagnostic checklist", "Replacement parts breakdown", "Digital warranty record"],
    bestFor: ["Cars", "Autocare", "Mechanics", "Auto Electricians"],
  },
  SUBSCRIPTION_PICKUP: {
    key: "SUBSCRIPTION_PICKUP",
    label: "Recurring Domestic & Laundry Pickup",
    badge: "Recurring Care",
    color: "#06B6D4",
    description: "Bag volume estimator, wash & fold / dry-cleaning tiering, recurring weekly schedule, and doorstep collection.",
    features: ["Recurring pickup cadence", "Garment count & special care tags", "Express turnaround toggle", "Subscription billing sync"],
    bestFor: ["Laundry", "Dry Cleaning", "Wardrobe", "Sanitation"],
  },
  TECHNICAL_ESTIMATE_QUOTE: {
    key: "TECHNICAL_ESTIMATE_QUOTE",
    label: "Technical Estimate & Scope of Work",
    badge: "Field Contracting",
    color: "#1A56DB",
    description: "Scope specification form, material procurement quote, on-site technician survey request, and milestone escrow.",
    features: ["Site inspection booking", "Milestone payment schedule", "Material + labor quote breakdown", "Escrow release on completion"],
    bestFor: ["Handyman", "Specialists", "Solar", "Construction", "Corporate", "Tech"],
  },
};

export interface VerticalSector {
  id: string;
  slug: string;
  name: string;
  heroTitle: string;
  color: string;
  iconName: string;
  description: string;
  totalSubcategories: number;
  activeMerchants: number;
  monthlyGMV: string;
  defaultLayout: VerticalLayoutTemplate;
  status: "ACTIVE" | "MAINTENANCE" | "BETA";
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_VERTICALS: VerticalSector[] = [
  {
    id: "vert-01",
    slug: "home-services",
    name: "Home & Maintenance",
    heroTitle: "Reliable Help for Every Home & Compound",
    color: "#1A56DB",
    iconName: "Home",
    description: "Plumbing, electrical, solar, generator, carpentry, AC repair, and professional sanitation.",
    totalSubcategories: 3,
    activeMerchants: 342,
    monthlyGMV: "₦18,400,000",
    defaultLayout: "TECHNICAL_ESTIMATE_QUOTE",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-02",
    slug: "fashion-grooming",
    name: "Fashion & Grooming",
    heroTitle: "Bespoke Style, Beauty & Wardrobe Care",
    color: "#EC4899",
    iconName: "Scissors",
    description: "Bespoke tailoring, barbering, hair braiding, makeup artists, nail care, and laundry.",
    totalSubcategories: 2,
    activeMerchants: 215,
    monthlyGMV: "₦14,200,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-03",
    slug: "professional-services",
    name: "Professional Services",
    heroTitle: "Top-Tier Tech, Legal & Corporate Advisory",
    color: "#7E3AF2",
    iconName: "Briefcase",
    description: "Software developers, UI/UX, corporate lawyers, accountants, copywriters, and talent.",
    totalSubcategories: 4,
    activeMerchants: 184,
    monthlyGMV: "₦22,800,000",
    defaultLayout: "TECHNICAL_ESTIMATE_QUOTE",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-04",
    slug: "education-skills",
    name: "Education & Skills",
    heroTitle: "Empowering Tutoring & Vocational Masterclasses",
    color: "#0E9F6E",
    iconName: "GraduationCap",
    description: "Private home tutors, exam preparation, languages, driving schools, and coding bootcamps.",
    totalSubcategories: 2,
    activeMerchants: 140,
    monthlyGMV: "₦9,600,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-05",
    slug: "events-entertainment",
    name: "Events & Entertainment",
    heroTitle: "Celebrate Milestones & Grand Occasions",
    color: "#D97706",
    iconName: "Sparkles",
    description: "Event planners, decorators, DJs, MCs, photographers, videographers, and live bands.",
    totalSubcategories: 2,
    activeMerchants: 168,
    monthlyGMV: "₦16,500,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-06",
    slug: "health-wellness",
    name: "Health & Wellness",
    heroTitle: "Clinical Healthcare, Therapy & Domestic Care",
    color: "#0694A2",
    iconName: "HeartPulse",
    description: "Private nurses, physiotherapists, dentists, gym trainers, nannies, and care companions.",
    totalSubcategories: 3,
    activeMerchants: 125,
    monthlyGMV: "₦11,300,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-07",
    slug: "logistics-transport",
    name: "Logistics & Transport",
    heroTitle: "Zonal Route Dispatch, Haulage & Transit",
    color: "#3B82F6",
    iconName: "Truck",
    description: "Same-day dispatch riders, errand runners, moving relocations, drivers, and towing vans.",
    totalSubcategories: 2,
    activeMerchants: 195,
    monthlyGMV: "₦26,700,000",
    defaultLayout: "ON_DEMAND_DISPATCH",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-08",
    slug: "automotive-services",
    name: "Automotive Services",
    heroTitle: "Expert Mechanics, Detailing & Security",
    color: "#F59E0B",
    iconName: "Car",
    description: "Car mechanics, vulcanizers, panel beaters, mobile wash, and GPS car tracker installers.",
    totalSubcategories: 2,
    activeMerchants: 152,
    monthlyGMV: "₦15,100,000",
    defaultLayout: "VEHICLE_INSPECTION_LISTING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-09",
    slug: "food-agribusiness",
    name: "Food & Agribusiness",
    heroTitle: "Farm-to-Table Culinary & Agro Operations",
    color: "#EF4444",
    iconName: "UtensilsCrossed",
    description: "Private chefs, event caterers, custom cake bakers, bulk foodstuffs, and farm management.",
    totalSubcategories: 2,
    activeMerchants: 230,
    monthlyGMV: "₦21,400,000",
    defaultLayout: "QUICK_ORDER_FOOD",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-10",
    slug: "real-estate-construction",
    name: "Real Estate & Construction",
    heroTitle: "Property Discovery, Surveying & Civil Works",
    color: "#10B981",
    iconName: "Building2",
    description: "Estate agents, facility managers, land surveyors, architects, bricklayers, and POP installers.",
    totalSubcategories: 2,
    activeMerchants: 178,
    monthlyGMV: "₦32,500,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
];

export interface SubcategoryItem {
  id: string;
  slug: string;
  name: string;
  parentVerticalSlug: string;
  parentVerticalName: string;
  layoutTemplate: VerticalLayoutTemplate;
  highRecurring: boolean;
  recurringTag?: string;
  description: string;
  commissionRate: number; // Percentage, e.g. 7.5
  servicesCount: number;
  services: string[];
  activeMerchants: number;
  monthlyBookings: number;
  status: "ACTIVE" | "INACTIVE";
  seoMetaTitle: string;
  seoMetaDescription: string;
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_SUBCATEGORIES: SubcategoryItem[] = [
  // 1. Home & Maintenance
  {
    id: "sub-01",
    slug: "handyman",
    name: "Handyman Services",
    parentVerticalSlug: "home-services",
    parentVerticalName: "Home & Maintenance",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Household repairs, electrical wiring, plumbing leaks, woodwork, and welding.",
    commissionRate: 8.0,
    servicesCount: 6,
    services: ["Plumber Finder", "Electrician Finder", "Carpenter Finder", "Painter Finder", "Tiler Finder", "Welder Finder"],
    activeMerchants: 145,
    monthlyBookings: 1240,
    status: "ACTIVE",
    seoMetaTitle: "Verified Handyman, Plumbers & Electricians in Nigeria | Ofia Compass",
    seoMetaDescription: "Find background-checked plumbers, electricians, carpenters, and painters with escrow protection.",
    subdomainEnabled: true,
  },
  {
    id: "sub-02",
    slug: "specialists",
    name: "Technical Specialists",
    parentVerticalSlug: "home-services",
    parentVerticalName: "Home & Maintenance",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Solar inverters, power generators, HVAC air conditioning, and borehole drilling.",
    commissionRate: 7.0,
    servicesCount: 5,
    services: ["Solar Installer Finder", "Generator Repairer Finder", "AC Technician Finder", "Borehole Driller Finder", "Inverter Repairer Finder"],
    activeMerchants: 112,
    monthlyBookings: 860,
    status: "ACTIVE",
    seoMetaTitle: "Solar Inverter & Generator Technicians | Ofia Compass",
    seoMetaDescription: "Book certified solar energy installers, generator technicians, and borehole drillers across Lagos and Abuja.",
    subdomainEnabled: true,
  },
  {
    id: "sub-03",
    slug: "cleaning",
    name: "Sanitation & Cleaning",
    parentVerticalSlug: "home-services",
    parentVerticalName: "Home & Maintenance",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Recurring Deep Clean",
    description: "Deep house cleaning, fumigation pest control, waste disposal, and water tank washing.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Home Cleaner Finder", "Fumigator Finder", "Waste Disposal Finder", "Water Tank Cleaner Finder"],
    activeMerchants: 85,
    monthlyBookings: 1420,
    status: "ACTIVE",
    seoMetaTitle: "Deep Cleaning & Fumigation Pest Control | Ofia Compass",
    seoMetaDescription: "Schedule regular home cleaning, pest fumigation, and industrial waste disposal with vetted professionals.",
    subdomainEnabled: true,
  },

  // 2. Fashion & Grooming
  {
    id: "sub-04",
    slug: "beauty",
    name: "Style & Personal Care",
    parentVerticalSlug: "fashion-grooming",
    parentVerticalName: "Fashion & Grooming",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Bi-Weekly Appointment",
    description: "Bespoke tailoring, barbering, hair braiding, manicure/pedicure, and bridal makeup.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Bespoke Tailor Finder", "Hairdresser / Braider Finder", "Barber Finder", "Makeup Artist Finder", "Manicurist / Nail Tech Finder"],
    activeMerchants: 130,
    monthlyBookings: 2850,
    status: "ACTIVE",
    seoMetaTitle: "Bespoke Tailors, Barbers & Makeup Artists | Ofia Compass",
    seoMetaDescription: "Book top-rated bespoke fashion designers, barbers, braiders, and makeup artists.",
    subdomainEnabled: true,
  },
  {
    id: "sub-05",
    slug: "laundry",
    name: "Wardrobe & Laundry",
    parentVerticalSlug: "fashion-grooming",
    parentVerticalName: "Fashion & Grooming",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Weekly Doorstep Pickup",
    description: "Dry cleaning, express wash & fold, personal shopping, and cobbler shoe repair.",
    commissionRate: 12.0,
    servicesCount: 4,
    services: ["Laundry Finder", "Dry Cleaner Finder", "Personal Shopper Finder", "Cobbler / Shoe Repair Finder"],
    activeMerchants: 85,
    monthlyBookings: 3100,
    status: "ACTIVE",
    seoMetaTitle: "Doorstep Laundry & Dry Cleaning Services | Ofia Compass",
    seoMetaDescription: "Schedule weekly wash & fold laundry, dry cleaning, and cobbler repairs with doorstep pickup.",
    subdomainEnabled: true,
  },

  // 3. Professional Services
  {
    id: "sub-06",
    slug: "tech",
    name: "Tech & Software",
    parentVerticalSlug: "professional-services",
    parentVerticalName: "Professional Services",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Full-stack web developers, mobile apps, UI/UX designers, SEO, and cybersecurity.",
    commissionRate: 8.0,
    servicesCount: 5,
    services: ["Web Developer Finder", "App Developer Finder", "UI/UX Designer Finder", "SEO Expert Finder", "Cybersecurity Consultant Finder"],
    activeMerchants: 68,
    monthlyBookings: 430,
    status: "ACTIVE",
    seoMetaTitle: "Hire Top Nigerian Software Engineers & UI/UX Designers | Ofia Compass",
    seoMetaDescription: "Vetted freelance developers, React/Node engineers, and cybersecurity specialists for project contracts.",
    subdomainEnabled: true,
  },
  {
    id: "sub-07",
    slug: "corporate",
    name: "Corporate & Legal",
    parentVerticalSlug: "professional-services",
    parentVerticalName: "Professional Services",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Corporate lawyers, chartered accountants, tax consultants, and grant proposal writers.",
    commissionRate: 8.0,
    servicesCount: 5,
    services: ["Lawyer Finder", "Accountant Finder", "Tax Consultant Finder", "Business Consultant Finder", "Grant Writer Finder"],
    activeMerchants: 52,
    monthlyBookings: 320,
    status: "ACTIVE",
    seoMetaTitle: "Corporate Lawyers, Tax Consultants & Accountants | Ofia Compass",
    seoMetaDescription: "CAC business incorporation, audit preparation, corporate taxation, and business plan drafting.",
    subdomainEnabled: true,
  },
  {
    id: "sub-08",
    slug: "creative",
    name: "Creative & Content",
    parentVerticalSlug: "professional-services",
    parentVerticalName: "Professional Services",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: true,
    recurringTag: "Monthly Content Retainer",
    description: "Direct-response copywriters, social media managers, graphic designers, and video editors.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Copywriter Finder", "Social Media Manager Finder", "Graphic Designer Finder", "Video Editor Finder", "Translator Finder"],
    activeMerchants: 45,
    monthlyBookings: 680,
    status: "ACTIVE",
    seoMetaTitle: "Content Creators, Video Editors & Copywriters | Ofia Compass",
    seoMetaDescription: "Hire creative content talent for brand commercials, social reels, and ad copy.",
    subdomainEnabled: true,
  },
  {
    id: "sub-09",
    slug: "talent",
    name: "Commercial Talent",
    parentVerticalSlug: "professional-services",
    parentVerticalName: "Professional Services",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Commercial models, brand ambassadors, voice-over narrators, and actors.",
    commissionRate: 15.0,
    servicesCount: 3,
    services: ["Model Finder", "Actor Finder", "Voice-Over Artist Finder"],
    activeMerchants: 19,
    monthlyBookings: 180,
    status: "ACTIVE",
    seoMetaTitle: "Commercial Models & Voice-Over Artists | Ofia Compass",
    seoMetaDescription: "Book vetted voice-over artists and commercial talent for marketing campaigns.",
    subdomainEnabled: true,
  },

  // 4. Education & Skills
  {
    id: "sub-10",
    slug: "tutoring",
    name: "Academic Tutoring",
    parentVerticalSlug: "education-skills",
    parentVerticalName: "Education & Skills",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Monthly Term Tuition",
    description: "Private home tutors (K-12, WAEC, JAMB, IGCSE), language teachers, and music instructors.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Home Tutor Finder", "Exam Prep Tutor Finder", "Language Teacher Finder", "Music Instructor Finder", "Private School Finder"],
    activeMerchants: 82,
    monthlyBookings: 1840,
    status: "ACTIVE",
    seoMetaTitle: "Home Tutors for WAEC, JAMB, IGCSE & Music | Ofia Compass",
    seoMetaDescription: "Book qualified home tutors and music instructors for personal one-on-one sessions.",
    subdomainEnabled: true,
  },
  {
    id: "sub-11",
    slug: "vocational",
    name: "Vocational Training",
    parentVerticalSlug: "education-skills",
    parentVerticalName: "Education & Skills",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Certified driving instructors, coding trainers, fashion schools, and catering academies.",
    commissionRate: 8.0,
    servicesCount: 4,
    services: ["Driving School Instructor Finder", "Tech Skill Trainer Finder", "Fashion School Instructor Finder", "Catering School Instructor Finder"],
    activeMerchants: 58,
    monthlyBookings: 510,
    status: "ACTIVE",
    seoMetaTitle: "Driving Schools & Vocational Skill Academies | Ofia Compass",
    seoMetaDescription: "Enroll in verified driving schools and skill training centers with practical certifications.",
    subdomainEnabled: true,
  },

  // 5. Events & Entertainment
  {
    id: "sub-12",
    slug: "planning",
    name: "Event Planning & Decor",
    parentVerticalSlug: "events-entertainment",
    parentVerticalName: "Events & Entertainment",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Wedding planning, corporate event coordinators, stage decorators, and ushering agencies.",
    commissionRate: 7.5,
    servicesCount: 4,
    services: ["Event Planner Finder", "Decorator Finder", "Souvenir Vendor Finder", "Ushering Agency Finder"],
    activeMerchants: 74,
    monthlyBookings: 620,
    status: "ACTIVE",
    seoMetaTitle: "Event Planners, Decorators & Ushering Agencies | Ofia Compass",
    seoMetaDescription: "Book trusted planners, floral decorators, and event ushers for corporate events and weddings.",
    subdomainEnabled: true,
  },
  {
    id: "sub-13",
    slug: "entertainment",
    name: "Event Entertainment",
    parentVerticalSlug: "events-entertainment",
    parentVerticalName: "Events & Entertainment",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Professional DJs, hypemen MCs, photographers, videographers, drone pilots, and live bands.",
    commissionRate: 8.0,
    servicesCount: 6,
    services: ["DJ Finder", "MC Finder", "Photographer Finder", "Videographer Finder", "Drone Pilot Finder", "Live Band Finder"],
    activeMerchants: 94,
    monthlyBookings: 1150,
    status: "ACTIVE",
    seoMetaTitle: "Event DJs, MCs, Photographers & Live Bands | Ofia Compass",
    seoMetaDescription: "Hire top wedding photographers, event DJs, hype MCs, and live musical bands.",
    subdomainEnabled: true,
  },

  // 6. Health & Wellness
  {
    id: "sub-14",
    slug: "medical",
    name: "Medical Care",
    parentVerticalSlug: "health-wellness",
    parentVerticalName: "Health & Wellness",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Recurring Home Nurse",
    description: "Home duty nurses, physiotherapists, dentists, opticians, and neighborhood pharmacies.",
    commissionRate: 6.0,
    servicesCount: 5,
    services: ["Private Nurse Finder", "Physiotherapist Finder", "Dentist Finder", "Optician Finder", "Pharmacy Finder"],
    activeMerchants: 48,
    monthlyBookings: 790,
    status: "ACTIVE",
    seoMetaTitle: "Private Nurses, Physiotherapists & Medical Services | Ofia Compass",
    seoMetaDescription: "Book licensed private nurses and physical therapists for home healthcare.",
    subdomainEnabled: true,
  },
  {
    id: "sub-15",
    slug: "wellness",
    name: "Fitness & Wellness",
    parentVerticalSlug: "health-wellness",
    parentVerticalName: "Health & Wellness",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Weekly Gym/Yoga Session",
    description: "Personal gym instructors, yoga coaches, clinical nutritionists, and massage therapists.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Gym Instructor Finder", "Yoga Teacher Finder", "Nutritionist Finder", "Massage Therapist Finder"],
    activeMerchants: 42,
    monthlyBookings: 1250,
    status: "ACTIVE",
    seoMetaTitle: "Personal Gym Trainers & Massage Therapists | Ofia Compass",
    seoMetaDescription: "Hire fitness instructors, nutritionists, and therapeutic spa masseuses.",
    subdomainEnabled: true,
  },
  {
    id: "sub-16",
    slug: "caregiving",
    name: "Family & Childcare",
    parentVerticalSlug: "health-wellness",
    parentVerticalName: "Health & Wellness",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Monthly Nanny Retainer",
    description: "Background-checked nannies, elderly care companions, and domestic pet sitters.",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Nanny Finder", "Elderly Companion Finder", "Pet Sitter Finder"],
    activeMerchants: 35,
    monthlyBookings: 620,
    status: "ACTIVE",
    seoMetaTitle: "Certified Nannies, Elderly Companions & Pet Sitters | Ofia Compass",
    seoMetaDescription: "Find verified child caregivers and elderly companions with background verification.",
    subdomainEnabled: true,
  },

  // 7. Logistics & Transport
  {
    id: "sub-17",
    slug: "dispatch",
    name: "Courier & Dispatch",
    parentVerticalSlug: "logistics-transport",
    parentVerticalName: "Logistics & Transport",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily E-Commerce Courier",
    description: "Same-day motorbike dispatch riders, errand runners, and apartment relocation movers.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Dispatch Rider Finder", "Errand Runner Finder", "Moving / Relocation Service Finder"],
    activeMerchants: 110,
    monthlyBookings: 5400,
    status: "ACTIVE",
    seoMetaTitle: "Instant Dispatch Riders & Home Movers in Nigeria | Ofia Compass",
    seoMetaDescription: "Request same-day delivery dispatch riders and professional relocation movers with live GPS tracking.",
    subdomainEnabled: true,
  },
  {
    id: "sub-18",
    slug: "transport",
    name: "Transit & Rides",
    parentVerticalSlug: "logistics-transport",
    parentVerticalName: "Logistics & Transport",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily Commute & Chauffeur",
    description: "Corporate chauffeurs, emergency vehicle towing vans, car rentals, and bus hire charters.",
    commissionRate: 8.0,
    servicesCount: 4,
    services: ["Professional Driver Finder", "Towing Van Finder", "Car Rental Finder", "Bus Hire Finder"],
    activeMerchants: 85,
    monthlyBookings: 2100,
    status: "ACTIVE",
    seoMetaTitle: "Professional Drivers, Towing Vans & Car Rentals | Ofia Compass",
    seoMetaDescription: "Hire vetted personal drivers, emergency roadside towing vans, and car rentals.",
    subdomainEnabled: true,
  },

  // 8. Automotive Services
  {
    id: "sub-19",
    slug: "mechanics",
    name: "Auto Mechanics & Repair",
    parentVerticalSlug: "automotive-services",
    parentVerticalName: "Automotive Services",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: false,
    description: "Auto mechanical repairs, vulcanizing, panel beating, and auto electrical diagnostics.",
    commissionRate: 7.5,
    servicesCount: 4,
    services: ["Car Mechanic Finder", "Vulcanizer Finder", "Panel Beater Finder", "Auto Electrician Finder"],
    activeMerchants: 92,
    monthlyBookings: 1480,
    status: "ACTIVE",
    seoMetaTitle: "Car Mechanics, Vulcanizers & Auto Electricians | Ofia Compass",
    seoMetaDescription: "Connect with certified Japanese/German auto mechanics and mobile diagnostic technicians.",
    subdomainEnabled: true,
  },
  {
    id: "sub-20",
    slug: "autocare",
    name: "Auto Care & Tracking",
    parentVerticalSlug: "automotive-services",
    parentVerticalName: "Automotive Services",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: true,
    recurringTag: "Weekly Mobile Car Detailing",
    description: "Mobile doorstep car detailing, GPS vehicle trackers, and security dashcam installations.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Mobile Car Wash Finder", "Car Tracker Installer Finder", "Vehicle CCTV / Dashcam Installer Finder"],
    activeMerchants: 60,
    monthlyBookings: 1980,
    status: "ACTIVE",
    seoMetaTitle: "Mobile Car Wash & GPS Tracker Installation | Ofia Compass",
    seoMetaDescription: "Order doorstep mobile car wash detailing and vehicle security GPS tracker installation.",
    subdomainEnabled: true,
  },

  // 9. Food & Agribusiness
  {
    id: "sub-21",
    slug: "culinary",
    name: "Culinary & Catering",
    parentVerticalSlug: "food-agribusiness",
    parentVerticalName: "Food & Agribusiness",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: true,
    recurringTag: "Daily / Weekly Meal Ordering",
    description: "Private home chefs, event catering, celebration cakes, and wholesale foodstuff supply.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Private Chef Finder", "Event Caterer Finder", "Cake Baker Finder", "Bulk Food Supplier Finder"],
    activeMerchants: 145,
    monthlyBookings: 4600,
    status: "ACTIVE",
    seoMetaTitle: "Private Chefs, Event Caterers & Custom Cake Bakers | Ofia Compass",
    seoMetaDescription: "Order fresh meals from private chefs, custom birthday cakes, and bulk foodstuff delivery.",
    subdomainEnabled: true,
  },
  {
    id: "sub-22",
    slug: "agriculture",
    name: "Farming & Agro-Processing",
    parentVerticalSlug: "food-agribusiness",
    parentVerticalName: "Food & Agribusiness",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Commercial farm management, agro-processing, veterinary doctors, poultry, and fish farming.",
    commissionRate: 5.0,
    servicesCount: 6,
    services: ["Farm Manager Finder", "Agro-Processor Finder", "Veterinary Doctor Finder", "Pet Groomer Finder", "Poultry Farmer Finder", "Fish Farmer Finder"],
    activeMerchants: 85,
    monthlyBookings: 720,
    status: "ACTIVE",
    seoMetaTitle: "Farm Managers, Veterinarians & Agro Suppliers | Ofia Compass",
    seoMetaDescription: "Connect with agricultural consultants, veterinary doctors, and bulk livestock suppliers.",
    subdomainEnabled: true,
  },

  // 10. Real Estate & Construction
  {
    id: "sub-23",
    slug: "properties",
    name: "Properties & Shortlets",
    parentVerticalSlug: "real-estate-construction",
    parentVerticalName: "Real Estate & Construction",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Shortlet / Apartment Stays",
    description: "Verified shortlet apartments, commercial leasing, property management, and land surveys.",
    commissionRate: 5.0,
    servicesCount: 4,
    services: ["Estate Agent Finder", "Facility Manager Finder", "Land Surveyor Finder", "Quantity Surveyor Finder"],
    activeMerchants: 108,
    monthlyBookings: 2450,
    status: "ACTIVE",
    seoMetaTitle: "Shortlet Apartments, Property Agents & Land Surveyors | Ofia Compass",
    seoMetaDescription: "Discover luxury shortlet apartments, verified property listings, and chartered land surveyors.",
    subdomainEnabled: true,
  },
  {
    id: "sub-24",
    slug: "construction",
    name: "Civil Construction & POP",
    parentVerticalSlug: "real-estate-construction",
    parentVerticalName: "Real Estate & Construction",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Architectural blueprints, bricklaying, aluminum glass fitting, and POP ceiling artistry.",
    commissionRate: 6.5,
    servicesCount: 4,
    services: ["Architect Finder", "Bricklayer Finder", "Aluminum & Glass Fitter Finder", "POP Ceiling Installer Finder"],
    activeMerchants: 70,
    monthlyBookings: 890,
    status: "ACTIVE",
    seoMetaTitle: "Architects, Bricklayers & POP Ceiling Installers | Ofia Compass",
    seoMetaDescription: "Hire registered architects, building contractors, and interior POP ceiling specialists.",
    subdomainEnabled: true,
  },
];
