export type VerticalLayoutTemplate =
  | "ON_DEMAND_DISPATCH"
  | "QUICK_ORDER_FOOD"
  | "CALENDAR_BOOKING"
  | "RENTAL_STAY_BOOKING"
  | "VEHICLE_INSPECTION_LISTING"
  | "SUBSCRIPTION_PICKUP"
  | "TECHNICAL_ESTIMATE_QUOTE";

export interface LayoutTemplateMeta {
  key: VerticalLayoutTemplate;
  label: string;
  badge: string;
  color: string;
  description: string;
  features: string[];
  bestFor: string[];
}

export const LAYOUT_TEMPLATES_CATALOG: Record<VerticalLayoutTemplate, LayoutTemplateMeta> = {
  QUICK_ORDER_FOOD: {
    key: "QUICK_ORDER_FOOD",
    label: "Quick-Order Restaurant / Kitchen",
    badge: "Food & Menu",
    color: "#EF4444",
    description: "Visual item menu grid, instant cart drawer, preparation time estimator, and kitchen rider dispatch.",
    features: ["Dish customization & add-ons", "Real-time kitchen order ticket", "Live delivery tracking", "Dietary badges (Halal, Vegan)"],
    bestFor: ["Food", "Restaurants", "Kitchens", "Catering", "Bakers"],
  },
  RENTAL_STAY_BOOKING: {
    key: "RENTAL_STAY_BOOKING",
    label: "Shortlet, Hotel & Property Stays",
    badge: "Hospitality & Stays",
    color: "#059669",
    description: "Check-in/out date range picker, nightly rate multiplier, guest count, amenity filters, and security deposit escrow.",
    features: ["Date range calendar", "High-res photo walkthroughs", "House rules agreement", "Automated security deposit hold"],
    bestFor: ["Hotels", "Apartments", "Properties", "Shortlets", "Villas"],
  },
  ON_DEMAND_DISPATCH: {
    key: "ON_DEMAND_DISPATCH",
    label: "On-Demand Route, Rides & Courier Dispatch",
    badge: "Rides & Courier",
    color: "#3B82F6",
    description: "Live map radius lookup, instant distance fare computation, courier dispatch desk, and waybill barcode tracking.",
    features: ["Map pickup & dropoff pins", "Automated zonal rate engine", "Live rider telemetry", "Digital proof of delivery (POD)"],
    bestFor: ["Rides", "Dispatch", "Chauffeurs", "Movers", "Courier"],
  },
  CALENDAR_BOOKING: {
    key: "CALENDAR_BOOKING",
    label: "Calendar Slot & Specialist Booking",
    badge: "Appointments",
    color: "#8B5CF6",
    description: "Interactive time-slot selector, specialist staff picker, service duration calculator, and booking deposit escrow.",
    features: ["Stylist / Tutor selection", "Instant calendar availability", "Automated SMS/WhatsApp reminders", "Partial deposit escrow"],
    bestFor: ["Beauty", "Tutors", "Salons", "Barbers", "Spas", "Private Lessons"],
  },
  VEHICLE_INSPECTION_LISTING: {
    key: "VEHICLE_INSPECTION_LISTING",
    label: "Automotive Inspection & Workshop Bay",
    badge: "Auto & Detailing",
    color: "#D97706",
    description: "Vehicle VIN/plate lookup, mileage selector, multi-point diagnostic bay report, and quote approval.",
    features: ["VIN & engine spec lookup", "Multi-point diagnostic checklist", "Replacement parts breakdown", "Digital warranty record"],
    bestFor: ["Cars", "Autocare", "Mechanics", "Mobile Detailing", "Trackers"],
  },
  SUBSCRIPTION_PICKUP: {
    key: "SUBSCRIPTION_PICKUP",
    label: "Recurring Doorstep Laundry & Wardrobe Pickup",
    badge: "Recurring Care",
    color: "#06B6D4",
    description: "Bag volume estimator, wash & fold / dry-cleaning tiering, recurring weekly schedule, and doorstep collection.",
    features: ["Recurring pickup cadence", "Garment count & special care tags", "Express turnaround toggle", "Subscription billing sync"],
    bestFor: ["Laundry", "Dry Cleaning", "Sneakers Care", "Ironing"],
  },
  TECHNICAL_ESTIMATE_QUOTE: {
    key: "TECHNICAL_ESTIMATE_QUOTE",
    label: "Technical Estimate & Scope of Work",
    badge: "Field Contracting",
    color: "#1A56DB",
    description: "Scope specification form, material procurement quote, on-site technician survey request, and milestone escrow.",
    features: ["Site inspection booking", "Milestone payment schedule", "Material + labor quote breakdown", "Escrow release on completion"],
    bestFor: ["Commercial Real Estate", "Land Surveying", "Heavy Haulage"],
  },
};

export interface VerticalSector {
  id: string;
  slug: string;
  name: string;
  heroTitle: string;
  color: string;
  iconName: string;
  description: string;
  totalSubcategories: number;
  activeMerchants: number;
  monthlyGMV: string;
  defaultLayout: VerticalLayoutTemplate;
  status: "ACTIVE" | "MAINTENANCE" | "BETA";
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_VERTICALS: VerticalSector[] = [
  {
    id: "vert-food",
    slug: "food",
    name: "Food",
    heroTitle: "Order from Top Kitchens, Fast Casual & Private Chefs",
    color: "#EF4444",
    iconName: "UtensilsCrossed",
    description: "Fast-food restaurants, cloud kitchens, private home chefs, gourmet caterers, and artisan cake bakers.",
    totalSubcategories: 5,
    activeMerchants: 310,
    monthlyGMV: "₦28,400,000",
    defaultLayout: "QUICK_ORDER_FOOD",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-hotels",
    slug: "hotels",
    name: "Hotels",
    heroTitle: "Luxury Resorts, Boutique Hotels & City Lodges",
    color: "#059669",
    iconName: "Building2",
    description: "Verified luxury hotel suites, boutique lodges, seaside resorts, conference lodgings, and weekend getaways.",
    totalSubcategories: 4,
    activeMerchants: 145,
    monthlyGMV: "₦34,200,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-rides",
    slug: "rides",
    name: "Rides",
    heroTitle: "City Transit, Airport Chauffeurs & Executive Car Hire",
    color: "#3B82F6",
    iconName: "Car",
    description: "On-demand city rides, executive chauffeurs, airport pickup transfers, charter buses, and roadside towing.",
    totalSubcategories: 4,
    activeMerchants: 220,
    monthlyGMV: "₦38,500,000",
    defaultLayout: "ON_DEMAND_DISPATCH",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-dispatch",
    slug: "dispatch",
    name: "Dispatch",
    heroTitle: "Instant Motorbike Couriers, Errands & Relocation Movers",
    color: "#2563EB",
    iconName: "Truck",
    description: "Same-day motorbike dispatch delivery, express errand runners, heavy haulage, and home relocation movers.",
    totalSubcategories: 4,
    activeMerchants: 280,
    monthlyGMV: "₦42,100,000",
    defaultLayout: "ON_DEMAND_DISPATCH",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-beauty",
    slug: "beauty",
    name: "Beauty",
    heroTitle: "Hair Salons, Barbers, Braiders & Bridal Makeup",
    color: "#EC4899",
    iconName: "Scissors",
    description: "Professional hairstylists, master barbers, hair braiders, bridal makeup artists, nail salons, and luxury spas.",
    totalSubcategories: 6,
    activeMerchants: 295,
    monthlyGMV: "₦26,800,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-apartments",
    slug: "apartments",
    name: "Apartments",
    heroTitle: "Verified Shortlet Flats, Serviced Studios & Luxury Penthouses",
    color: "#10B981",
    iconName: "Home",
    description: "Daily shortlet apartments, fully furnished serviced studios, luxury vacation penthouses, and corporate stays.",
    totalSubcategories: 4,
    activeMerchants: 190,
    monthlyGMV: "₦46,300,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-cars",
    slug: "cars",
    name: "Cars",
    heroTitle: "Certified Auto Mechanics, Diagnostics & Spare Parts",
    color: "#F59E0B",
    iconName: "Wrench",
    description: "Japanese and German car mechanics, auto electricians, spray panel beaters, mobile vulcanizers, and diagnostic bays.",
    totalSubcategories: 4,
    activeMerchants: 165,
    monthlyGMV: "₦24,600,000",
    defaultLayout: "VEHICLE_INSPECTION_LISTING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-laundry",
    slug: "laundry",
    name: "Laundry",
    heroTitle: "Doorstep Wash & Fold, Dry Cleaning & Sneaker Spa",
    color: "#06B6D4",
    iconName: "Sparkles",
    description: "Scheduled doorstep laundry collection, express dry cleaning, wedding gown care, and sneaker restoration.",
    totalSubcategories: 4,
    activeMerchants: 130,
    monthlyGMV: "₦18,900,000",
    defaultLayout: "SUBSCRIPTION_PICKUP",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-tutors",
    slug: "tutors",
    name: "Tutors",
    heroTitle: "Home Tutors for WAEC, JAMB, IGCSE, Coding & Languages",
    color: "#8B5CF6",
    iconName: "GraduationCap",
    description: "Private K-12 home tutors, exam preparation specialists, instrument music teachers, coding mentors, and language instructors.",
    totalSubcategories: 5,
    activeMerchants: 175,
    monthlyGMV: "₦15,700,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-autocare",
    slug: "autocare",
    name: "Autocare",
    heroTitle: "Mobile Doorstep Car Wash, Detailing & GPS Trackers",
    color: "#D97706",
    iconName: "ShieldCheck",
    description: "Doorstep waterless mobile detailing, ceramic paint coating, anti-theft GPS trackers, and vehicular security dashcams.",
    totalSubcategories: 4,
    activeMerchants: 110,
    monthlyGMV: "₦14,400,000",
    defaultLayout: "VEHICLE_INSPECTION_LISTING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-properties",
    slug: "properties",
    name: "Properties",
    heroTitle: "Real Estate Brokerage, Commercial Leasing & Land Surveying",
    color: "#7E3AF2",
    iconName: "Building2",
    description: "Residential real estate sales, commercial office leasing, chartered land surveyors, and corporate facility management.",
    totalSubcategories: 4,
    activeMerchants: 140,
    monthlyGMV: "₦52,000,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
];

export interface SubcategoryItem {
  id: string;
  slug: string;
  name: string;
  parentVerticalSlug: string;
  parentVerticalName: string;
  layoutTemplate: VerticalLayoutTemplate;
  highRecurring: boolean;
  recurringTag?: string;
  description: string;
  commissionRate: number; // Percentage, e.g. 7.5
  servicesCount: number;
  services: string[];
  activeMerchants: number;
  monthlyBookings: number;
  status: "ACTIVE" | "INACTIVE";
  seoMetaTitle: string;
  seoMetaDescription: string;
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_SUBCATEGORIES: SubcategoryItem[] = [
  // 1. Food
  {
    id: "sub-food-01",
    slug: "restaurants",
    name: "Restaurants & Fast Casual",
    parentVerticalSlug: "food",
    parentVerticalName: "Food",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: true,
    recurringTag: "Daily Lunch & Dinner",
    description: "Fast-food takeaways, African delicacy spots, burger joints, and cloud kitchens.",
    commissionRate: 12.0,
    servicesCount: 5,
    services: ["Jollof Spot", "Grilled Catfish Point", "Shawarma & Wraps", "Continental Dine-In", "Breakfast Cafe"],
    activeMerchants: 120,
    monthlyBookings: 8400,
    status: "ACTIVE",
    seoMetaTitle: "Order Fast Food & Restaurant Delivery in Nigeria | Ofia Food",
    seoMetaDescription: "Browse menus, customize dishes, and order express doorstep food delivery.",
    subdomainEnabled: true,
  },
  {
    id: "sub-food-02",
    slug: "chefs",
    name: "Private Chefs & Cooks",
    parentVerticalSlug: "food",
    parentVerticalName: "Food",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: true,
    recurringTag: "Weekly Home Meal Prep",
    description: "Hired private chefs for home cooking, gourmet date nights, and family weekly soup batches.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Private Chef Booking", "Weekly Soup Cook", "Diet Meal Prep", "Private Dining Specialist"],
    activeMerchants: 65,
    monthlyBookings: 1850,
    status: "ACTIVE",
    seoMetaTitle: "Hire Private Home Chefs in Lagos & Abuja | Ofia Food",
    seoMetaDescription: "Book certified private chefs for in-house meal prep and fine dining.",
    subdomainEnabled: true,
  },
  {
    id: "sub-food-03",
    slug: "bakers",
    name: "Custom Cake Bakers",
    parentVerticalSlug: "food",
    parentVerticalName: "Food",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: true,
    recurringTag: "Celebration Cakes",
    description: "Custom birthday cakes, wedding tiers, cupcakes, and artisan pastries.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Custom Cake Baker", "Wedding Cake Designer", "Pastry & Dessert Chef"],
    activeMerchants: 80,
    monthlyBookings: 2400,
    status: "ACTIVE",
    seoMetaTitle: "Custom Birthday Cakes & Pastry Bakers | Ofia Food",
    seoMetaDescription: "Order custom celebration cakes with custom toppings and express delivery.",
    subdomainEnabled: true,
  },
  {
    id: "sub-food-04",
    slug: "caterers",
    name: "Event Caterers",
    parentVerticalSlug: "food",
    parentVerticalName: "Food",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: false,
    description: "Full-scale corporate buffet catering, traditional wedding food trays, and small chops.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Buffet Caterer", "Small Chops Vendor", "Cocktail & Mocktail Bar"],
    activeMerchants: 45,
    monthlyBookings: 920,
    status: "ACTIVE",
    seoMetaTitle: "Event Food Caterers & Small Chops Vendors | Ofia Food",
    seoMetaDescription: "Hire wedding and corporate party food caterers with tasting sessions.",
    subdomainEnabled: true,
  },

  // 2. Hotels
  {
    id: "sub-hotel-01",
    slug: "luxury-hotels",
    name: "Luxury & Business Hotels",
    parentVerticalSlug: "hotels",
    parentVerticalName: "Hotels",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Corporate & Weekend Stays",
    description: "4-star and 5-star business hotels with conference centers, gyms, and breakfast buffets.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Executive Suite", "Deluxe Room", "Presidential Suite", "Conference Hall"],
    activeMerchants: 55,
    monthlyBookings: 1950,
    status: "ACTIVE",
    seoMetaTitle: "Luxury Business Hotels in Lagos & Abuja | Ofia Hotels",
    seoMetaDescription: "Instant booking for luxury hotel rooms with free cancellation and airport transfers.",
    subdomainEnabled: true,
  },
  {
    id: "sub-hotel-02",
    slug: "resorts",
    name: "Seaside Resorts & Lodges",
    parentVerticalSlug: "hotels",
    parentVerticalName: "Hotels",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Weekend Getaways",
    description: "Private beach resorts, nature eco-lodges, and holiday villas with infinity pools.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Beach Cabin", "Lagoon Chalet", "Poolside Suite"],
    activeMerchants: 40,
    monthlyBookings: 1300,
    status: "ACTIVE",
    seoMetaTitle: "Beach Resorts & Getaway Lodges in Nigeria | Ofia Hotels",
    seoMetaDescription: "Escape to private beachside chalets and eco-lodges.",
    subdomainEnabled: true,
  },
  {
    id: "sub-hotel-03",
    slug: "boutique-hotels",
    name: "Boutique & Budget Lodges",
    parentVerticalSlug: "hotels",
    parentVerticalName: "Hotels",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Short Stays",
    description: "Aesthetic boutique hotels and clean transit lodges with 24/7 power and security.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Studio Room", "Standard Suite", "Transit Pod"],
    activeMerchants: 50,
    monthlyBookings: 2200,
    status: "ACTIVE",
    seoMetaTitle: "Boutique Hotels & Lodgings | Ofia Hotels",
    seoMetaDescription: "Affordable and cozy boutique hotels for travelers.",
    subdomainEnabled: true,
  },

  // 3. Rides
  {
    id: "sub-rides-01",
    slug: "chauffeurs",
    name: "Executive Chauffeurs & Drivers",
    parentVerticalSlug: "rides",
    parentVerticalName: "Rides",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily Corporate Commute",
    description: "Vetted executive personal drivers for full-day corporate hire and interstate trips.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Full-Day Driver", "Interstate Chauffeur", "Executive SUV Hire", "Wedding Motorcade"],
    activeMerchants: 90,
    monthlyBookings: 3200,
    status: "ACTIVE",
    seoMetaTitle: "Hire Executive Chauffeurs & Drivers in Nigeria | Ofia Rides",
    seoMetaDescription: "Background-checked professional drivers for daily and interstate trips.",
    subdomainEnabled: true,
  },
  {
    id: "sub-rides-02",
    slug: "airport-transfer",
    name: "Airport Pickup & Transfers",
    parentVerticalSlug: "rides",
    parentVerticalName: "Rides",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Flight Arrival Transfers",
    description: "Guaranteed on-time airport dropoff and arrival pickups with flight tracking.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Airport Pickup", "Airport Dropoff", "Luggage Van Transit"],
    activeMerchants: 70,
    monthlyBookings: 2800,
    status: "ACTIVE",
    seoMetaTitle: "Airport Taxi & Executive Transfers in Lagos & Abuja | Ofia Rides",
    seoMetaDescription: "Pre-book airport transit with flight delay monitoring.",
    subdomainEnabled: true,
  },
  {
    id: "sub-rides-03",
    slug: "towing",
    name: "Emergency Towing Vans",
    parentVerticalSlug: "rides",
    parentVerticalName: "Rides",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: false,
    description: "24/7 flatbed emergency vehicle recovery, accident towing, and roadside transit.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Flatbed Tow Truck", "Wheel-Lift Recovery", "Heavy Vehicle Haul"],
    activeMerchants: 60,
    monthlyBookings: 1400,
    status: "ACTIVE",
    seoMetaTitle: "Emergency Roadside Towing Trucks | Ofia Rides",
    seoMetaDescription: "Fast breakdown towing and vehicle recovery within 30 minutes.",
    subdomainEnabled: true,
  },

  // 4. Dispatch
  {
    id: "sub-dispatch-01",
    slug: "bike-couriers",
    name: "Motorbike Dispatch Riders",
    parentVerticalSlug: "dispatch",
    parentVerticalName: "Dispatch",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily E-Commerce Deliveries",
    description: "Instant same-day motorbike courier dispatch with GPS route tracking and waybills.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Instant Delivery Rider", "Same-Day Parcel Courier", "Scheduled Merchant Route"],
    activeMerchants: 150,
    monthlyBookings: 14500,
    status: "ACTIVE",
    seoMetaTitle: "Same-Day Motorbike Dispatch Delivery in Nigeria | Ofia Dispatch",
    seoMetaDescription: "Request express dispatch riders with instant fare calculation.",
    subdomainEnabled: true,
  },
  {
    id: "sub-dispatch-02",
    slug: "errands",
    name: "Errand Runners",
    parentVerticalSlug: "dispatch",
    parentVerticalName: "Dispatch",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily Market Runs",
    description: "Market grocery shopping runners, bank document pick-ups, and custom errands.",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Market Grocery Runner", "Document Pickup", "Personal Errand Assistant"],
    activeMerchants: 70,
    monthlyBookings: 3200,
    status: "ACTIVE",
    seoMetaTitle: "Errand Runners for Market Shopping & Deliveries | Ofia Dispatch",
    seoMetaDescription: "Hire personal errand assistants for shopping and paperwork delivery.",
    subdomainEnabled: true,
  },
  {
    id: "sub-dispatch-03",
    slug: "movers",
    name: "Relocation & Home Movers",
    parentVerticalSlug: "dispatch",
    parentVerticalName: "Dispatch",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: false,
    description: "Full-service house moving trucks, packing boxes, furniture disassembly, and office relocations.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Home Relocation Truck", "Office Movers", "Packaging & Disassembly"],
    activeMerchants: 60,
    monthlyBookings: 980,
    status: "ACTIVE",
    seoMetaTitle: "Professional House Moving & Relocation Services | Ofia Dispatch",
    seoMetaDescription: "Move your apartment or office hassle-free with certified movers.",
    subdomainEnabled: true,
  },

  // 5. Beauty
  {
    id: "sub-beauty-01",
    slug: "hair-salons",
    name: "Hair Stylists & Braiders",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Bi-Weekly Hair Styling",
    description: "Knotless braids, wig revamping, hair installations, relaxing, and loc maintenance.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Knotless Braids", "Wig Installation", "Dreadlocks Stylist", "Natural Hair Treatment", "Weave Fixing"],
    activeMerchants: 110,
    monthlyBookings: 4200,
    status: "ACTIVE",
    seoMetaTitle: "Hair Braiders, Stylists & Wig Installers | Ofia Beauty",
    seoMetaDescription: "Book appointments with top hair braiders and salon stylists near you.",
    subdomainEnabled: true,
  },
  {
    id: "sub-beauty-02",
    slug: "barbers",
    name: "Executive Barbers",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Weekly Haircut & Beard Trim",
    description: "Precision fades, beard sculpting, hot towel grooming, and home visit barbering.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Executive Haircut", "Beard Sculpt & Dye", "Home Service Barber", "Kids Haircut"],
    activeMerchants: 95,
    monthlyBookings: 5100,
    status: "ACTIVE",
    seoMetaTitle: "Top Barbers & Grooming Salons in Nigeria | Ofia Beauty",
    seoMetaDescription: "Schedule haircuts and home grooming appointments.",
    subdomainEnabled: true,
  },
  {
    id: "sub-beauty-03",
    slug: "makeup-artists",
    name: "Makeup Artists & Gele",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Weekend Event Glam",
    description: "Bridal glam makeup, owambe party looks, photoshoot styling, and gele tying.",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Bridal Makeup", "Party Glam", "Gele Tying Specialist"],
    activeMerchants: 90,
    monthlyBookings: 2900,
    status: "ACTIVE",
    seoMetaTitle: "Bridal & Party Makeup Artists | Ofia Beauty",
    seoMetaDescription: "Hire top MUAs and gele specialists for weddings and celebrations.",
    subdomainEnabled: true,
  },

  // 6. Apartments
  {
    id: "sub-apt-01",
    slug: "shortlets",
    name: "Shortlet Flats & Studios",
    parentVerticalSlug: "apartments",
    parentVerticalName: "Apartments",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Weekly / Monthly Vacation Stays",
    description: "1, 2 & 3-bedroom fully serviced shortlet apartments with high-speed WiFi, Netflix, and 24/7 power.",
    commissionRate: 8.0,
    servicesCount: 4,
    services: ["1-Bedroom Serviced Flat", "2-Bedroom Shortlet", "3-Bedroom Luxury Apartment", "Studio Apartment"],
    activeMerchants: 110,
    monthlyBookings: 3800,
    status: "ACTIVE",
    seoMetaTitle: "Luxury Shortlet Apartments in Lekki, Ikoyi & Abuja | Ofia Apartments",
    seoMetaDescription: "Book verified shortlet apartments with instant confirmation.",
    subdomainEnabled: true,
  },
  {
    id: "sub-apt-02",
    slug: "villas",
    name: "Vacation Villas & Penthouses",
    parentVerticalSlug: "apartments",
    parentVerticalName: "Apartments",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Weekend Vacation Bookings",
    description: "Private detached vacation villas with private swimming pools, game rooms, and chef kitchens.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Poolside Villa", "Penthouse Suite", "Private Mansion"],
    activeMerchants: 80,
    monthlyBookings: 1400,
    status: "ACTIVE",
    seoMetaTitle: "Vacation Villas & Luxury Penthouses | Ofia Apartments",
    seoMetaDescription: "Rent private luxury villas for vacations and gatherings.",
    subdomainEnabled: true,
  },

  // 7. Cars
  {
    id: "sub-cars-01",
    slug: "mechanics",
    name: "Auto Mechanics & Engine Bay",
    parentVerticalSlug: "cars",
    parentVerticalName: "Cars",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: false,
    description: "Certified auto mechanics for engine overhauls, brake pad replacements, suspension, and routine oil servicing.",
    commissionRate: 7.5,
    servicesCount: 4,
    services: ["Engine Servicing", "Brake & Suspension Bay", "Transmission Repair", "Pre-Purchase Inspection"],
    activeMerchants: 95,
    monthlyBookings: 2400,
    status: "ACTIVE",
    seoMetaTitle: "Auto Mechanics & Car Servicing Centers in Nigeria | Ofia Cars",
    seoMetaDescription: "Book certified automobile repair technicians with warranty protection.",
    subdomainEnabled: true,
  },
  {
    id: "sub-cars-02",
    slug: "auto-electricians",
    name: "Auto Electricians & AC Repair",
    parentVerticalSlug: "cars",
    parentVerticalName: "Cars",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: false,
    description: "Car air conditioning regassing, computerized ECU scanning, wiring diagnostics, and alternator rebuilds.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["Car AC Regas & Repair", "ECU Computer Diagnostic", "Auto Electrician Wiring"],
    activeMerchants: 70,
    monthlyBookings: 1800,
    status: "ACTIVE",
    seoMetaTitle: "Car AC Technicians & Auto Electricians | Ofia Cars",
    seoMetaDescription: "Fast computerized auto diagnostic scanning and car AC gas refill.",
    subdomainEnabled: true,
  },

  // 8. Laundry
  {
    id: "sub-laundry-01",
    slug: "wash-and-fold",
    name: "Wash, Dry & Fold",
    parentVerticalSlug: "laundry",
    parentVerticalName: "Laundry",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Weekly Doorstep Bag Pickup",
    description: "Everyday garment wash, tumble dry, and crisp fold by weight (5kg, 10kg, 20kg bags).",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Everyday Wash & Fold Bag", "Bedsheet & Duvet Laundry", "Express 24-hr Wash"],
    activeMerchants: 70,
    monthlyBookings: 4600,
    status: "ACTIVE",
    seoMetaTitle: "Doorstep Wash & Fold Laundry Service | Ofia Laundry",
    seoMetaDescription: "Schedule recurring weekly laundry pickup with fresh folding.",
    subdomainEnabled: true,
  },
  {
    id: "sub-laundry-02",
    slug: "dry-cleaning",
    name: "Dry Cleaning & Suit Press",
    parentVerticalSlug: "laundry",
    parentVerticalName: "Laundry",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Corporate Apparel Care",
    description: "Eco-friendly dry cleaning for bespoke suits, agbada, senator wears, wedding gowns, and curtains.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Suit & Agbada Dry Clean", "Evening Gown Care", "Curtain & Rug Cleaning"],
    activeMerchants: 60,
    monthlyBookings: 3100,
    status: "ACTIVE",
    seoMetaTitle: "Suit Dry Cleaning & Agbada Steam Press | Ofia Laundry",
    seoMetaDescription: "Professional dry cleaning for executive apparel with doorstep delivery.",
    subdomainEnabled: true,
  },

  // 9. Tutors
  {
    id: "sub-tutor-01",
    slug: "academic-tutors",
    name: "K-12 & Exam Prep Tutors",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Monthly Term Tuition",
    description: "Private home tutors for Mathematics, Sciences, WAEC, JAMB, IGCSE, SAT, and IELTS.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["WAEC/JAMB Prep Tutor", "Primary & JSS Tutor", "IGCSE & Cambridge Tutor", "SAT/IELTS Coach"],
    activeMerchants: 95,
    monthlyBookings: 2800,
    status: "ACTIVE",
    seoMetaTitle: "Private Home Tutors for WAEC, JAMB & IGCSE | Ofia Tutors",
    seoMetaDescription: "Book background-checked home tutors for primary, secondary, and exam prep.",
    subdomainEnabled: true,
  },
  {
    id: "sub-tutor-02",
    slug: "coding-tutors",
    name: "Tech, Coding & Music Mentors",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Weekly Lessons",
    description: "Kids coding mentors (Python, Scratch, Web), piano and guitar instructors, and French language tutors.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Kids Coding Instructor", "Piano & Keyboard Teacher", "Guitar Lessons", "French & Spanish Tutor"],
    activeMerchants: 80,
    monthlyBookings: 1900,
    status: "ACTIVE",
    seoMetaTitle: "Kids Coding Mentors & Piano Music Instructors | Ofia Tutors",
    seoMetaDescription: "One-on-one personal instructors for practical tech and music skills.",
    subdomainEnabled: true,
  },

  // 10. Autocare
  {
    id: "sub-autocare-01",
    slug: "mobile-wash",
    name: "Doorstep Mobile Car Wash",
    parentVerticalSlug: "autocare",
    parentVerticalName: "Autocare",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: true,
    recurringTag: "Weekly Doorstep Car Wash",
    description: "Waterless doorstep mobile car wash, engine degreasing, leather conditioning, and interior vacuuming.",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Doorstep Wash & Vacuum", "Full Detailing & Engine Clean", "Ceramic Wax Buff"],
    activeMerchants: 60,
    monthlyBookings: 3400,
    status: "ACTIVE",
    seoMetaTitle: "Mobile Doorstep Car Wash & Detailing in Nigeria | Ofia Autocare",
    seoMetaDescription: "Have your car washed and detailed right at your home or office driveway.",
    subdomainEnabled: true,
  },
  {
    id: "sub-autocare-02",
    slug: "trackers",
    name: "GPS Trackers & Dashcams",
    parentVerticalSlug: "autocare",
    parentVerticalName: "Autocare",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: false,
    description: "Real-time GPS anti-theft tracking installation, remote engine kill switch, and dual 4K dashcams.",
    commissionRate: 8.0,
    servicesCount: 3,
    services: ["GPS Vehicle Tracker", "Remote Engine Kill Switch", "Dual Dashcam Installation"],
    activeMerchants: 50,
    monthlyBookings: 1600,
    status: "ACTIVE",
    seoMetaTitle: "GPS Vehicle Tracker & Security Dashcam Installation | Ofia Autocare",
    seoMetaDescription: "Protect your car with anti-theft GPS trackers and live mobile app monitoring.",
    subdomainEnabled: true,
  },

  // 11. Properties
  {
    id: "sub-prop-01",
    slug: "realty-sales",
    name: "Property Sales & Leasing",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: false,
    description: "Verified residential house sales, commercial office space leasing, and verified land plots.",
    commissionRate: 5.0,
    servicesCount: 4,
    services: ["Residential Sale Agent", "Commercial Leasing Broker", "Land Plot Verification", "Facility Manager"],
    activeMerchants: 80,
    monthlyBookings: 1200,
    status: "ACTIVE",
    seoMetaTitle: "Verified Property Sales & Commercial Leasing in Nigeria | Ofia Properties",
    seoMetaDescription: "Buy houses, rent offices, and verify genuine land titles with chartered agents.",
    subdomainEnabled: true,
  },
  {
    id: "sub-prop-02",
    slug: "surveyors",
    name: "Land Surveyors & Valuation",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Registered land surveyors for beacon placement, perimeter survey plans, and property valuation reports.",
    commissionRate: 6.0,
    servicesCount: 3,
    services: ["Registered Land Surveyor", "Property Valuation Assessor", "Topographical Survey"],
    activeMerchants: 60,
    monthlyBookings: 850,
    status: "ACTIVE",
    seoMetaTitle: "Registered Land Surveyors & Property Valuation | Ofia Properties",
    seoMetaDescription: "Chartered surveyors for land beaconing, deed searches, and building valuation.",
    subdomainEnabled: true,
  },
];
