export type VerticalLayoutTemplate =
  | "ON_DEMAND_DISPATCH"
  | "QUICK_ORDER_FOOD"
  | "CALENDAR_BOOKING"
  | "RENTAL_STAY_BOOKING"
  | "VEHICLE_INSPECTION_LISTING"
  | "SUBSCRIPTION_PICKUP"
  | "TECHNICAL_ESTIMATE_QUOTE";

export interface LayoutTemplateMeta {
  key: VerticalLayoutTemplate;
  label: string;
  badge: string;
  color: string;
  description: string;
  features: string[];
  bestFor: string[];
}

export const LAYOUT_TEMPLATES_CATALOG: Record<VerticalLayoutTemplate, LayoutTemplateMeta> = {
  QUICK_ORDER_FOOD: {
    key: "QUICK_ORDER_FOOD",
    label: "Quick-Order Restaurant / Kitchen",
    badge: "Food & Menu",
    color: "#EF4444",
    description: "Visual item menu grid, instant cart drawer, preparation time estimator, and kitchen rider dispatch.",
    features: ["Dish customization & add-ons", "Real-time kitchen order ticket", "Live delivery tracking", "Dietary badges (Halal, Vegan)"],
    bestFor: ["Food", "Culinary", "Restaurants", "Kitchens", "Catering", "Bakers"],
  },
  RENTAL_STAY_BOOKING: {
    key: "RENTAL_STAY_BOOKING",
    label: "Shortlet, Hotel & Property Stays",
    badge: "Hospitality & Stays",
    color: "#059669",
    description: "Check-in/out date range picker, nightly rate multiplier, guest count, amenity filters, and security deposit escrow.",
    features: ["Date range calendar", "High-res photo walkthroughs", "House rules agreement", "Automated security deposit hold"],
    bestFor: ["Hotels", "Apartments", "Properties", "Shortlets", "Villas"],
  },
  ON_DEMAND_DISPATCH: {
    key: "ON_DEMAND_DISPATCH",
    label: "On-Demand Route, Rides & Courier Dispatch",
    badge: "Rides & Courier",
    color: "#3B82F6",
    description: "Live map radius lookup, instant distance fare computation, courier dispatch desk, and waybill barcode tracking.",
    features: ["Map pickup & dropoff pins", "Automated zonal rate engine", "Live rider telemetry", "Digital proof of delivery (POD)"],
    bestFor: ["Rides", "Dispatch", "Transport", "Chauffeurs", "Movers", "Courier"],
  },
  CALENDAR_BOOKING: {
    key: "CALENDAR_BOOKING",
    label: "Calendar Slot & Specialist Booking",
    badge: "Appointments",
    color: "#8B5CF6",
    description: "Interactive time-slot selector, specialist staff picker, service duration calculator, and booking deposit escrow.",
    features: ["Stylist / Tutor selection", "Instant calendar availability", "Automated SMS/WhatsApp reminders", "Partial deposit escrow"],
    bestFor: ["Beauty", "Tutors", "Tutoring", "Wellness", "Medical", "Caregiving", "Salons", "Barbers", "Spas"],
  },
  VEHICLE_INSPECTION_LISTING: {
    key: "VEHICLE_INSPECTION_LISTING",
    label: "Automotive Inspection & Workshop Bay",
    badge: "Auto & Detailing",
    color: "#D97706",
    description: "Vehicle VIN/plate lookup, mileage selector, multi-point diagnostic bay report, and quote approval.",
    features: ["VIN & engine spec lookup", "Multi-point diagnostic checklist", "Replacement parts breakdown", "Digital warranty record"],
    bestFor: ["Cars", "Autocare", "Mechanics", "Mobile Detailing", "Trackers"],
  },
  SUBSCRIPTION_PICKUP: {
    key: "SUBSCRIPTION_PICKUP",
    label: "Recurring Doorstep Laundry & Wardrobe Pickup",
    badge: "Recurring Care",
    color: "#06B6D4",
    description: "Bag volume estimator, wash & fold / dry-cleaning tiering, recurring weekly schedule, and doorstep collection.",
    features: ["Recurring pickup cadence", "Garment count & special care tags", "Express turnaround toggle", "Subscription billing sync"],
    bestFor: ["Laundry", "Cleaning", "Dry Cleaning", "Sneakers Care", "Ironing"],
  },
  TECHNICAL_ESTIMATE_QUOTE: {
    key: "TECHNICAL_ESTIMATE_QUOTE",
    label: "Technical Estimate & Scope of Work",
    badge: "Field Contracting",
    color: "#1A56DB",
    description: "Scope specification form, material procurement quote, on-site technician survey request, and milestone escrow.",
    features: ["Site inspection booking", "Milestone payment schedule", "Material + labor quote breakdown", "Escrow release on completion"],
    bestFor: ["Handyman", "Specialists", "Construction", "Corporate", "Tech", "Agriculture", "Planning"],
  },
};

export interface VerticalSector {
  id: string;
  slug: string;
  name: string;
  heroTitle: string;
  color: string;
  iconName: string;
  description: string;
  totalSubcategories: number;
  activeMerchants: number;
  monthlyGMV: string;
  defaultLayout: VerticalLayoutTemplate;
  status: "ACTIVE" | "MAINTENANCE" | "BETA";
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_VERTICALS: VerticalSector[] = [
  {
    id: "vert-food",
    slug: "food",
    name: "Food",
    heroTitle: "Order from Top Kitchens, Fast Casual & Private Chefs",
    color: "#EF4444",
    iconName: "UtensilsCrossed",
    description: "Culinary dining, cloud kitchens, private home chefs, gourmet caterers, and artisan cake bakers.",
    totalSubcategories: 2,
    activeMerchants: 310,
    monthlyGMV: "₦28,400,000",
    defaultLayout: "QUICK_ORDER_FOOD",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-hotels",
    slug: "hotels",
    name: "Hotels",
    heroTitle: "Luxury Resorts, Boutique Hotels & City Lodges",
    color: "#059669",
    iconName: "Building2",
    description: "Verified luxury hotel suites, boutique lodges, seaside resorts, conference lodgings, and weekend getaways.",
    totalSubcategories: 2,
    activeMerchants: 145,
    monthlyGMV: "₦34,200,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-rides",
    slug: "rides",
    name: "Rides",
    heroTitle: "City Transit, Airport Chauffeurs & Executive Car Hire",
    color: "#3B82F6",
    iconName: "Car",
    description: "On-demand city transit, executive personal drivers, airport transfers, charter buses, and emergency towing.",
    totalSubcategories: 2,
    activeMerchants: 220,
    monthlyGMV: "₦38,500,000",
    defaultLayout: "ON_DEMAND_DISPATCH",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-dispatch",
    slug: "dispatch",
    name: "Dispatch",
    heroTitle: "Instant Motorbike Couriers, Errands & Relocation Movers",
    color: "#2563EB",
    iconName: "Truck",
    description: "Same-day motorbike dispatch delivery, express errand runners, heavy haulage, and home relocation movers.",
    totalSubcategories: 2,
    activeMerchants: 280,
    monthlyGMV: "₦42,100,000",
    defaultLayout: "ON_DEMAND_DISPATCH",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-beauty",
    slug: "beauty",
    name: "Beauty",
    heroTitle: "Hair Salons, Barbers, Braiders & Bridal Makeup",
    color: "#EC4899",
    iconName: "Scissors",
    description: "Professional hairstylists, master barbers, hair braiders, bridal makeup artists, nail salons, and luxury spas.",
    totalSubcategories: 3,
    activeMerchants: 295,
    monthlyGMV: "₦26,800,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-apartments",
    slug: "apartments",
    name: "Apartments",
    heroTitle: "Verified Shortlet Flats, Serviced Studios & Luxury Penthouses",
    color: "#10B981",
    iconName: "Home",
    description: "Daily shortlet apartments, fully furnished serviced studios, luxury vacation penthouses, and corporate stays.",
    totalSubcategories: 2,
    activeMerchants: 190,
    monthlyGMV: "₦46,300,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-cars",
    slug: "cars",
    name: "Cars",
    heroTitle: "Certified Auto Mechanics, Diagnostics & Spare Parts",
    color: "#F59E0B",
    iconName: "Wrench",
    description: "Auto mechanics, auto electricians, spray panel beaters, mobile vulcanizers, and diagnostic bays.",
    totalSubcategories: 2,
    activeMerchants: 165,
    monthlyGMV: "₦24,600,000",
    defaultLayout: "VEHICLE_INSPECTION_LISTING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-laundry",
    slug: "laundry",
    name: "Laundry",
    heroTitle: "Doorstep Wash & Fold, Dry Cleaning & Sneaker Spa",
    color: "#06B6D4",
    iconName: "Sparkles",
    description: "Scheduled doorstep laundry collection, express dry cleaning, wedding gown care, and sneaker restoration.",
    totalSubcategories: 2,
    activeMerchants: 130,
    monthlyGMV: "₦18,900,000",
    defaultLayout: "SUBSCRIPTION_PICKUP",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-tutors",
    slug: "tutors",
    name: "Tutors",
    heroTitle: "Home Tutors for WAEC, JAMB, IGCSE, Coding & Languages",
    color: "#8B5CF6",
    iconName: "GraduationCap",
    description: "Private K-12 home tutors, exam preparation specialists, instrument music teachers, coding mentors, and language instructors.",
    totalSubcategories: 2,
    activeMerchants: 175,
    monthlyGMV: "₦15,700,000",
    defaultLayout: "CALENDAR_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-autocare",
    slug: "autocare",
    name: "Autocare",
    heroTitle: "Mobile Doorstep Car Wash, Detailing & GPS Trackers",
    color: "#D97706",
    iconName: "ShieldCheck",
    description: "Doorstep waterless mobile detailing, ceramic paint coating, anti-theft GPS trackers, and vehicular security dashcams.",
    totalSubcategories: 2,
    activeMerchants: 110,
    monthlyGMV: "₦14,400,000",
    defaultLayout: "VEHICLE_INSPECTION_LISTING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
  {
    id: "vert-properties",
    slug: "properties",
    name: "Properties",
    heroTitle: "Real Estate Brokerage, Commercial Leasing & Land Surveying",
    color: "#7E3AF2",
    iconName: "Building2",
    description: "Residential real estate sales, commercial office leasing, chartered land surveyors, and civil building contracting.",
    totalSubcategories: 2,
    activeMerchants: 140,
    monthlyGMV: "₦52,000,000",
    defaultLayout: "RENTAL_STAY_BOOKING",
    status: "ACTIVE",
    subdomainEnabled: true,
  },
];

export interface SubcategoryItem {
  id: string;
  slug: string;
  name: string;
  parentVerticalSlug: string;
  parentVerticalName: string;
  layoutTemplate: VerticalLayoutTemplate;
  highRecurring: boolean;
  recurringTag?: string;
  description: string;
  commissionRate: number; // Percentage, e.g. 7.5
  servicesCount: number;
  services: string[];
  activeMerchants: number;
  monthlyBookings: number;
  status: "ACTIVE" | "INACTIVE";
  seoMetaTitle: string;
  seoMetaDescription: string;
  subdomainEnabled: boolean;
}

export const INITIAL_COMPASS_SUBCATEGORIES: SubcategoryItem[] = [
  // 1. Home & Maintenance
  {
    id: "sub-01",
    slug: "handyman",
    name: "Handyman Services",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties & Home",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Household repairs, electrical wiring, plumbing leaks, woodwork, and welding.",
    commissionRate: 8.0,
    servicesCount: 6,
    services: ["Plumber Finder", "Electrician Finder", "Carpenter Finder", "Painter Finder", "Tiler Finder", "Welder Finder"],
    activeMerchants: 145,
    monthlyBookings: 1240,
    status: "ACTIVE",
    seoMetaTitle: "Verified Handyman, Plumbers & Electricians in Nigeria | Ofia Compass",
    seoMetaDescription: "Find background-checked plumbers, electricians, carpenters, and painters with escrow protection.",
    subdomainEnabled: true,
  },
  {
    id: "sub-02",
    slug: "specialists",
    name: "Technical Specialists",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties & Home",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Solar inverters, power generators, HVAC air conditioning, and borehole drilling.",
    commissionRate: 7.0,
    servicesCount: 5,
    services: ["Solar Installer Finder", "Generator Repairer Finder", "AC Technician Finder", "Borehole Driller Finder", "Inverter Repairer Finder"],
    activeMerchants: 112,
    monthlyBookings: 860,
    status: "ACTIVE",
    seoMetaTitle: "Solar Inverter & Generator Technicians | Ofia Compass",
    seoMetaDescription: "Book certified solar energy installers, generator technicians, and borehole drillers across Lagos and Abuja.",
    subdomainEnabled: true,
  },
  {
    id: "sub-03",
    slug: "cleaning",
    name: "Sanitation & Hygiene",
    parentVerticalSlug: "laundry",
    parentVerticalName: "Laundry & Care",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Recurring Deep Clean",
    description: "Deep house cleaning, fumigation pest control, waste disposal, and water tank washing.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Home Cleaner Finder", "Fumigator Finder", "Waste Disposal Finder", "Water Tank Cleaner Finder"],
    activeMerchants: 85,
    monthlyBookings: 1420,
    status: "ACTIVE",
    seoMetaTitle: "Deep Cleaning & Fumigation Pest Control | Ofia Compass",
    seoMetaDescription: "Schedule regular home cleaning, pest fumigation, and industrial waste disposal with vetted professionals.",
    subdomainEnabled: true,
  },

  // 2. Fashion & Grooming
  {
    id: "sub-04",
    slug: "beauty",
    name: "Style & Personal Care",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Bi-Weekly Appointment",
    description: "Bespoke tailoring, barbering, hair braiding, manicure/pedicure, and bridal makeup.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Bespoke Tailor Finder", "Hairdresser / Braider Finder", "Barber Finder", "Makeup Artist Finder", "Manicurist / Nail Tech Finder"],
    activeMerchants: 130,
    monthlyBookings: 2850,
    status: "ACTIVE",
    seoMetaTitle: "Bespoke Tailors, Barbers & Makeup Artists | Ofia Beauty",
    seoMetaDescription: "Book top-rated bespoke fashion designers, barbers, braiders, and makeup artists.",
    subdomainEnabled: true,
  },
  {
    id: "sub-05",
    slug: "laundry",
    name: "Wardrobe & Apparel Care",
    parentVerticalSlug: "laundry",
    parentVerticalName: "Laundry",
    layoutTemplate: "SUBSCRIPTION_PICKUP",
    highRecurring: true,
    recurringTag: "Weekly Doorstep Pickup",
    description: "Dry cleaning, express wash & fold, personal shopping, and cobbler shoe repair.",
    commissionRate: 12.0,
    servicesCount: 4,
    services: ["Laundry Finder", "Dry Cleaner Finder", "Personal Shopper Finder", "Cobbler / Shoe Repair Finder"],
    activeMerchants: 85,
    monthlyBookings: 3100,
    status: "ACTIVE",
    seoMetaTitle: "Doorstep Laundry & Dry Cleaning Services | Ofia Laundry",
    seoMetaDescription: "Schedule weekly wash & fold laundry, dry cleaning, and cobbler repairs with doorstep pickup.",
    subdomainEnabled: true,
  },

  // 3. Professional Services
  {
    id: "sub-06",
    slug: "tech",
    name: "Tech & Software",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors & Tech",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Full-stack web developers, mobile apps, UI/UX designers, SEO, and cybersecurity.",
    commissionRate: 8.0,
    servicesCount: 5,
    services: ["Web Developer Finder", "App Developer Finder", "UI/UX Designer Finder", "SEO Expert Finder", "Cybersecurity Consultant Finder"],
    activeMerchants: 68,
    monthlyBookings: 430,
    status: "ACTIVE",
    seoMetaTitle: "Hire Top Nigerian Software Engineers & UI/UX Designers | Ofia Compass",
    seoMetaDescription: "Vetted freelance developers, React/Node engineers, and cybersecurity specialists for project contracts.",
    subdomainEnabled: true,
  },
  {
    id: "sub-07",
    slug: "corporate",
    name: "Corporate & Legal",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties & Corporate",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Corporate lawyers, chartered accountants, tax consultants, and grant proposal writers.",
    commissionRate: 8.0,
    servicesCount: 5,
    services: ["Lawyer Finder", "Accountant Finder", "Tax Consultant Finder", "Business Consultant Finder", "Grant Writer Finder"],
    activeMerchants: 52,
    monthlyBookings: 320,
    status: "ACTIVE",
    seoMetaTitle: "Corporate Lawyers, Tax Consultants & Accountants | Ofia Compass",
    seoMetaDescription: "CAC business incorporation, audit preparation, corporate taxation, and business plan drafting.",
    subdomainEnabled: true,
  },
  {
    id: "sub-08",
    slug: "creative",
    name: "Creative & Media",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty & Creative",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: true,
    recurringTag: "Monthly Content Retainer",
    description: "Direct-response copywriters, social media managers, graphic designers, and video editors.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Copywriter Finder", "Social Media Manager Finder", "Graphic Designer Finder", "Video Editor Finder", "Translator Finder"],
    activeMerchants: 45,
    monthlyBookings: 680,
    status: "ACTIVE",
    seoMetaTitle: "Content Creators, Video Editors & Copywriters | Ofia Compass",
    seoMetaDescription: "Hire creative content talent for brand commercials, social reels, and ad copy.",
    subdomainEnabled: true,
  },
  {
    id: "sub-09",
    slug: "talent",
    name: "Commercial Talent",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Beauty & Talent",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Commercial models, brand ambassadors, voice-over narrators, and actors.",
    commissionRate: 15.0,
    servicesCount: 3,
    services: ["Model Finder", "Actor Finder", "Voice-Over Artist Finder"],
    activeMerchants: 19,
    monthlyBookings: 180,
    status: "ACTIVE",
    seoMetaTitle: "Commercial Models & Voice-Over Artists | Ofia Compass",
    seoMetaDescription: "Book vetted voice-over artists and commercial talent for marketing campaigns.",
    subdomainEnabled: true,
  },

  // 4. Education & Skills
  {
    id: "sub-10",
    slug: "tutoring",
    name: "Academic Tutoring",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Monthly Term Tuition",
    description: "Private home tutors (K-12, WAEC, JAMB, IGCSE), language teachers, and music instructors.",
    commissionRate: 10.0,
    servicesCount: 5,
    services: ["Home Tutor Finder", "Exam Prep Tutor Finder", "Language Teacher Finder", "Music Instructor Finder", "Private School Finder"],
    activeMerchants: 82,
    monthlyBookings: 1840,
    status: "ACTIVE",
    seoMetaTitle: "Home Tutors for WAEC, JAMB, IGCSE & Music | Ofia Tutors",
    seoMetaDescription: "Book qualified home tutors and music instructors for personal one-on-one sessions.",
    subdomainEnabled: true,
  },
  {
    id: "sub-11",
    slug: "vocational",
    name: "Vocational Training",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Certified driving instructors, coding trainers, fashion schools, and catering academies.",
    commissionRate: 8.0,
    servicesCount: 4,
    services: ["Driving School Instructor Finder", "Tech Skill Trainer Finder", "Fashion School Instructor Finder", "Catering School Instructor Finder"],
    activeMerchants: 58,
    monthlyBookings: 510,
    status: "ACTIVE",
    seoMetaTitle: "Driving Schools & Vocational Skill Academies | Ofia Tutors",
    seoMetaDescription: "Enroll in verified driving schools and skill training centers with practical certifications.",
    subdomainEnabled: true,
  },

  // 5. Events & Entertainment
  {
    id: "sub-12",
    slug: "planning",
    name: "Event Planning",
    parentVerticalSlug: "hotels",
    parentVerticalName: "Hotels & Events",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Wedding planning, corporate event coordinators, stage decorators, and ushering agencies.",
    commissionRate: 7.5,
    servicesCount: 4,
    services: ["Event Planner Finder", "Decorator Finder", "Souvenir Vendor Finder", "Ushering Agency Finder"],
    activeMerchants: 74,
    monthlyBookings: 620,
    status: "ACTIVE",
    seoMetaTitle: "Event Planners, Decorators & Ushering Agencies | Ofia Compass",
    seoMetaDescription: "Book trusted planners, floral decorators, and event ushers for corporate events and weddings.",
    subdomainEnabled: true,
  },
  {
    id: "sub-13",
    slug: "entertainment",
    name: "Entertainment & Media",
    parentVerticalSlug: "hotels",
    parentVerticalName: "Hotels & Entertainment",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: false,
    description: "Professional DJs, hypemen MCs, photographers, videographers, drone pilots, and live bands.",
    commissionRate: 8.0,
    servicesCount: 6,
    services: ["DJ Finder", "MC Finder", "Photographer Finder", "Videographer Finder", "Drone Pilot Finder", "Live Band Finder"],
    activeMerchants: 94,
    monthlyBookings: 1150,
    status: "ACTIVE",
    seoMetaTitle: "Event DJs, MCs, Photographers & Live Bands | Ofia Compass",
    seoMetaDescription: "Hire top wedding photographers, event DJs, hype MCs, and live musical bands.",
    subdomainEnabled: true,
  },

  // 6. Health & Wellness
  {
    id: "sub-14",
    slug: "medical",
    name: "Medical Care",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Health & Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Recurring Home Nurse",
    description: "Home duty nurses, physiotherapists, dentists, opticians, and neighborhood pharmacies.",
    commissionRate: 6.0,
    servicesCount: 5,
    services: ["Private Nurse Finder", "Physiotherapist Finder", "Dentist Finder", "Optician Finder", "Pharmacy Finder"],
    activeMerchants: 48,
    monthlyBookings: 790,
    status: "ACTIVE",
    seoMetaTitle: "Private Nurses, Physiotherapists & Medical Services | Ofia Compass",
    seoMetaDescription: "Book licensed private nurses and physical therapists for home healthcare.",
    subdomainEnabled: true,
  },
  {
    id: "sub-15",
    slug: "wellness",
    name: "Fitness & Bodywork",
    parentVerticalSlug: "beauty",
    parentVerticalName: "Health & Beauty",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Weekly Gym/Yoga Session",
    description: "Personal gym instructors, yoga coaches, clinical nutritionists, and massage therapists.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Gym Instructor Finder", "Yoga Teacher Finder", "Nutritionist Finder", "Massage Therapist Finder"],
    activeMerchants: 42,
    monthlyBookings: 1250,
    status: "ACTIVE",
    seoMetaTitle: "Personal Gym Trainers & Massage Therapists | Ofia Compass",
    seoMetaDescription: "Hire fitness instructors, nutritionists, and therapeutic spa masseuses.",
    subdomainEnabled: true,
  },
  {
    id: "sub-16",
    slug: "caregiving",
    name: "Family & Childcare",
    parentVerticalSlug: "tutors",
    parentVerticalName: "Tutors & Care",
    layoutTemplate: "CALENDAR_BOOKING",
    highRecurring: true,
    recurringTag: "Monthly Nanny Retainer",
    description: "Background-checked nannies, elderly care companions, and domestic pet sitters.",
    commissionRate: 12.0,
    servicesCount: 3,
    services: ["Nanny Finder", "Elderly Companion Finder", "Pet Sitter Finder"],
    activeMerchants: 35,
    monthlyBookings: 620,
    status: "ACTIVE",
    seoMetaTitle: "Certified Nannies, Elderly Companions & Pet Sitters | Ofia Compass",
    seoMetaDescription: "Find verified child caregivers and elderly companions with background verification.",
    subdomainEnabled: true,
  },

  // 7. Logistics & Transport
  {
    id: "sub-17",
    slug: "dispatch",
    name: "Courier & Moving",
    parentVerticalSlug: "dispatch",
    parentVerticalName: "Dispatch",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily E-Commerce Courier",
    description: "Same-day motorbike dispatch riders, errand runners, and apartment relocation movers.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Dispatch Rider Finder", "Errand Runner Finder", "Moving / Relocation Service Finder"],
    activeMerchants: 110,
    monthlyBookings: 5400,
    status: "ACTIVE",
    seoMetaTitle: "Instant Dispatch Riders & Home Movers in Nigeria | Ofia Dispatch",
    seoMetaDescription: "Request same-day delivery dispatch riders and professional relocation movers with live GPS tracking.",
    subdomainEnabled: true,
  },
  {
    id: "sub-18",
    slug: "transport",
    name: "Transit & Vehicle Hire",
    parentVerticalSlug: "rides",
    parentVerticalName: "Rides",
    layoutTemplate: "ON_DEMAND_DISPATCH",
    highRecurring: true,
    recurringTag: "Daily Commute & Chauffeur",
    description: "Corporate chauffeurs, emergency vehicle towing vans, car rentals, and charter buses.",
    commissionRate: 8.0,
    servicesCount: 4,
    services: ["Professional Driver Finder", "Towing Van Finder", "Car Rental Finder", "Bus Hire Finder"],
    activeMerchants: 85,
    monthlyBookings: 2100,
    status: "ACTIVE",
    seoMetaTitle: "Professional Drivers, Towing Vans & Car Rentals | Ofia Rides",
    seoMetaDescription: "Hire vetted personal drivers, emergency roadside towing vans, and car rentals.",
    subdomainEnabled: true,
  },

  // 8. Automotive Services
  {
    id: "sub-19",
    slug: "mechanics",
    name: "Auto Repairs",
    parentVerticalSlug: "cars",
    parentVerticalName: "Cars",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: false,
    description: "Auto mechanical repairs, vulcanizing, panel beating, and auto electrical diagnostics.",
    commissionRate: 7.5,
    servicesCount: 4,
    services: ["Car Mechanic Finder", "Vulcanizer Finder", "Panel Beater Finder", "Auto Electrician Finder"],
    activeMerchants: 92,
    monthlyBookings: 1480,
    status: "ACTIVE",
    seoMetaTitle: "Car Mechanics, Vulcanizers & Auto Electricians | Ofia Cars",
    seoMetaDescription: "Connect with certified Japanese/German auto mechanics and mobile diagnostic technicians.",
    subdomainEnabled: true,
  },
  {
    id: "sub-20",
    slug: "autocare",
    name: "Auto Care & Security",
    parentVerticalSlug: "autocare",
    parentVerticalName: "Autocare",
    layoutTemplate: "VEHICLE_INSPECTION_LISTING",
    highRecurring: true,
    recurringTag: "Weekly Mobile Car Detailing",
    description: "Mobile doorstep car detailing, GPS vehicle trackers, and vehicular security dashcam installations.",
    commissionRate: 10.0,
    servicesCount: 3,
    services: ["Mobile Car Wash Finder", "Car Tracker Installer Finder", "Vehicle CCTV / Dashcam Installer Finder"],
    activeMerchants: 60,
    monthlyBookings: 1980,
    status: "ACTIVE",
    seoMetaTitle: "Mobile Car Wash & GPS Tracker Installation | Ofia Autocare",
    seoMetaDescription: "Order doorstep mobile car wash detailing and vehicle security GPS tracker installation.",
    subdomainEnabled: true,
  },

  // 9. Food & Agribusiness
  {
    id: "sub-21",
    slug: "culinary",
    name: "Culinary & Catering",
    parentVerticalSlug: "food",
    parentVerticalName: "Food",
    layoutTemplate: "QUICK_ORDER_FOOD",
    highRecurring: true,
    recurringTag: "Daily / Weekly Meal Ordering",
    description: "Private home chefs, event catering, celebration cakes, and wholesale foodstuff supply.",
    commissionRate: 10.0,
    servicesCount: 4,
    services: ["Private Chef Finder", "Event Caterer Finder", "Cake Baker Finder", "Bulk Food Supplier Finder"],
    activeMerchants: 145,
    monthlyBookings: 4600,
    status: "ACTIVE",
    seoMetaTitle: "Private Chefs, Event Caterers & Custom Cake Bakers | Ofia Food",
    seoMetaDescription: "Order fresh meals from private chefs, custom birthday cakes, and bulk foodstuff delivery.",
    subdomainEnabled: true,
  },
  {
    id: "sub-22",
    slug: "agriculture",
    name: "Farming & Livestock",
    parentVerticalSlug: "food",
    parentVerticalName: "Food & Agro",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Commercial farm management, agro-processing, veterinary medicine, pet grooming, poultry, and fish farming.",
    commissionRate: 5.0,
    servicesCount: 6,
    services: ["Farm Manager Finder", "Agro-Processor Finder", "Veterinary Doctor Finder", "Pet Groomer Finder", "Poultry Farmer Finder", "Fish Farmer Finder"],
    activeMerchants: 85,
    monthlyBookings: 720,
    status: "ACTIVE",
    seoMetaTitle: "Farm Managers, Veterinarians & Agro Suppliers | Ofia Food",
    seoMetaDescription: "Connect with agricultural consultants, veterinary doctors, and bulk livestock suppliers.",
    subdomainEnabled: true,
  },

  // 10. Real Estate & Construction
  {
    id: "sub-23",
    slug: "properties",
    name: "Property & Agency",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties",
    layoutTemplate: "RENTAL_STAY_BOOKING",
    highRecurring: true,
    recurringTag: "Shortlet / Apartment Stays",
    description: "Verified shortlet apartments, commercial leasing, property management, and land surveys.",
    commissionRate: 5.0,
    servicesCount: 4,
    services: ["Estate Agent Finder", "Facility Manager Finder", "Land Surveyor Finder", "Quantity Surveyor Finder"],
    activeMerchants: 108,
    monthlyBookings: 2450,
    status: "ACTIVE",
    seoMetaTitle: "Shortlet Apartments, Property Agents & Land Surveyors | Ofia Properties",
    seoMetaDescription: "Discover luxury shortlet apartments, verified property listings, and chartered land surveyors.",
    subdomainEnabled: true,
  },
  {
    id: "sub-24",
    slug: "construction",
    name: "Building & Civil Contracting",
    parentVerticalSlug: "properties",
    parentVerticalName: "Properties & Building",
    layoutTemplate: "TECHNICAL_ESTIMATE_QUOTE",
    highRecurring: false,
    description: "Architectural blueprints, bricklaying, aluminum glass fitting, and POP ceiling artistry.",
    commissionRate: 6.5,
    servicesCount: 4,
    services: ["Architect Finder", "Bricklayer Finder", "Aluminum & Glass Fitter Finder", "POP Ceiling Installer Finder"],
    activeMerchants: 70,
    monthlyBookings: 890,
    status: "ACTIVE",
    seoMetaTitle: "Architects, Bricklayers & POP Ceiling Installers | Ofia Properties",
    seoMetaDescription: "Hire registered architects, building contractors, and interior POP ceiling specialists.",
    subdomainEnabled: true,
  },
];
