name: mobile_driver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: 6.2.1
  flexicon: ^0.8.0
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.2
  google_maps_flutter: ^2.18.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Dropa
      fonts:
        - asset: assets/fonts/Dropa-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/final_app_icon.png"
  min_sdk_android: 21
